---
name: Bundle-Theory
version: 1.07
author:
  - 'David E. Wheeler <david@kineticode.com>'
abstract: A bundle to install all of Theory's favorite modules
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Module::Build: 0.2701
  Test::More: 0.17
recommends:
  Test::Pod: 1.20
configure_requires:
  Module::Build: 0.2701
provides:
  Bundle::Theory:
    file: lib/Bundle/Theory.pm
    version: 1.07
  Bundle::Theory::Apache:
    file: lib/Bundle/Theory/Apache.pm
    version: 1.07
  Bundle::Theory::Apache2:
    file: lib/Bundle/Theory/Apache2.pm
    version: 1.07
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
